server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
spring:
  application.name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  pathsToMarch:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true
security:
  jwt:
    token:
      expire-length: 3600000 #1h
    key:
      public: classpath:app.pub
      private: classpath:app.key
